[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
tokio-utils.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
sockit.workspace = true
